# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: loshermanossinespagueti
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: nodesmith
service: nodesmith-backend

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2

functions:
  app:
    handler: server.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-offline
